version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wiki1_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: rails
    volumes:
      - mysqlsockdir:/var/run/mysqld
    network_mode: none
  rails:
    build: .
    volumes:
      - mysqlsockdir:/var/run/mysqld
    ports:
      - "3000:3000"
    network_mode: bridge
    depends_on:
      - mysql
volumes:
  mysqlsockdir:

