name: DeployToAppEngine

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - id: secrets
        uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
        with:
          secrets: |-
            master_key:${{ secrets.GCP_PROJECT_ID }}/${{ secrets.MASTER_KEY_ID }}
      - run: echo $RAILS_MASTER_KEY > config/master.key
        env:
          RAILS_MASTER_KEY: ${{ steps.secrets.outputs.master_key }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - run: |
          gem install bundler
          bundle install
      - run: gcloud app deploy --quiet
      - run: bundle exec rails appengine:exec -- bundle exec rails db:migrate
